[general]
startup = [
    "st",
    "st",
    "st",
    "st",
    "feh --randomize --bg-scale ~/.local/share/backgrounds/*",
]

bindings = [
    { mod = 0xffeb, keysym = 0xFF0D, action = { type = "run", target = "kitty" } },
]

[general.border]
width = 2
active_color = 0xffeb231
inactive_color = 0x483D8B
radius = 20

[general.window]
gap = 30
