[general]
startup = [
    "kitty",
    "kitty",
    "kitty",
    "google-chrome",
    "feh --randomize --bg-scale ~/.local/share/backgrounds/*",
]

bindings = [
    { mod = 0xffeb, keysym = 0xFF0D, action = { type = "run", target = "kitty" } },  
]

[general.border]
width = 2 
color = 0x880808
radius = 20 

[general.window]
gap = 30 