
[general]
startup = [
    "kitty",
    "kitty",
    "google-chrome",
    "feh --randomize --bg-scale ~/.local/share/backgrounds/*",
]

bindings = [
    { mod = 0xffeb, keysym = 0xFF0D, action = { type = "run", target = "kitty" } },  # Mod+Return
]


[general.border]
width = 2 # 2 pixels
color = 0x880808
radius = 20 # 20 pixels

[general.window]
gap = 30 # 20 pixels
