Helios: WindowManager Class Reference
WindowManager Class Reference
This class implements a window manager.
#include "helios.h"
Public Member Functions
void run ()
Starts the window manager.
WindowManager ()
Constructs a new WindowManager instance.
~WindowManager ()
Destructs the WindowManager instance.
Private Member Functions
void handle_destroy_notify (xcb_window_t window)
Handles a destroy notify event for the given window.
void handle_enter_notify (xcb_window_t window)
Handles an enter notify event for the given window.
void handle_key_press (xcb_key_press_event_t *key_press)
Handles a key press event for the given key press event.
void handle_map_request (xcb_window_t window)
Handles a map request event for the given window.
void handle_unmap_request (xcb_window_t window)
Handles an unmap request event for the given window.
void set_focus (xcb_window_t window)
Sets the focus of the window manager to the given window.
void set_window_border_color (xcb_window_t window, uint32_t color)
Sets the border color of the window to the given color.
void switch_workspace (uint32_t i)
Switches the workspace of the window manager to the given workspace.
void tile_windows ()
Tiles all windows in the current workspace.
Private Attributes
std::unique_ptr< xcb_atom_t[]> atoms
A unique pointer to an array of xcb_atom_t values.
Config config
The configuration for the window manager.
xcb_connection_t * conn
The XCB connection to the X server.
int current_window
The index of the window that currently has focus.
xcb_cursor_t cursor
The cursor ID for the window manager's cursor.
xcb_cursor_context_t * cursor_context
The context for the window manager's cursor.
uint32_t event_mask
The event mask for the window manager.
xcb_ewmh_connection_t ewmh
The EWMH connection for the window manager.
std::shared_ptr< spdlog::logger > logger
The logger for the window manager.
xcb_window_t root
The root window of the X server.
xcb_screen_t * screen
The screen structure for the screen that the window manager is managing.
std::vector< xcb_atom_t > supported_atoms = {}
A vector of supported atoms for the window manager.
std::unique_ptr< uint32_t[]> values
A unique pointer to an array of uint32_t values.
std::vector< xcb_window_t > windows
A vector of window IDs that the window manager is currently managing.
Detailed Description
This class implements a window manager.
It is responsible for managing the windows on the screen and handling events such as key presses.
Definition at line 29 of file helios.h.
Constructor & Destructor Documentation
WindowManager()
WindowManager::WindowManager ()
Constructs a new WindowManager instance.
Construct a new WindowManager object.
This constructor does not take any parameters. It initializes the window manager by connecting to the X server, setting up the event mask, and setting up the window manager's logger.
This function initializes a window manager, setting up the necessary XCB connections, loading the configuration, and preparing the window manager for use.
Exceptions
std::runtime_error if unable to connect to the X server
std::runtime_error if unable to initialize ewmh cookie for connection
std::runtime_error if unable to initialize ewmh connection with cookie
std::runtime_error if cursor context initialization fails
srd::runtime_error if cursor context creation fails
Definition at line 17 of file helios.cpp.
    : values(std::make_unique<uint32_t[]>(1)), atoms(nullptr) {
  logger->flush_on(spdlog::level::info);
  if (!(conn = xcb_connect(nullptr, nullptr))) {
    logger->error("Could not connect to the X server");
    throw std::runtime_error("X server connection failed");
  }
  config = loadConfig("config.toml");
  const xcb_setup_t *setup = xcb_get_setup(conn);
  if (xcb_connection_has_error(conn)) {
    logger->error(
        "The Connection has an error and other stuff could not be proceeded");
    exit(EXIT_FAILURE);
  }
  xcb_screen_iterator_t iter = xcb_setup_roots_iterator(setup);
  if (!(screen = iter.data)) {
    logger->error("Unable to access screen information. Ensure the X server is "
                  "running and is accessible");
  }
  xcb_flush(conn);
  root = screen->root;
  xcb_intern_atom_cookie_t *ewmh_cookie = new xcb_intern_atom_cookie_t;
  ewmh_cookie = xcb_ewmh_init_atoms(conn, &ewmh);
  if (!ewmh_cookie) {
    logger->error("EWMH cookie initialization failed");
    throw std::runtime_error("EWMH cookie initialization failed");
  }
  xcb_generic_error_t *error = nullptr;
  if (!xcb_ewmh_init_atoms_replies(&ewmh, ewmh_cookie, &error)) {
    if (error) {
      logger->error("EWMH initialization failed: {}", error->major_code);
      free(error);
    } else {
      logger->error(
          "EWMH initialization failed with no error details available");
    }
    throw std::runtime_error("EWMH connection initialization failed");
  }
  supported_atoms = {ewmh._NET_SUPPORTED,
                     ewmh._NET_SUPPORTING_WM_CHECK,
                     ewmh._NET_ACTIVE_WINDOW,
                     ewmh._NET_CLIENT_LIST,
                     ewmh._NET_CURRENT_DESKTOP,
                     ewmh._NET_DESKTOP_NAMES,
                     ewmh._NET_NUMBER_OF_DESKTOPS,
                     ewmh._NET_WM_NAME,
                     ewmh._NET_WM_STATE,
                     ewmh._NET_WM_STATE_FULLSCREEN,
                     ewmh._NET_WM_WINDOW_TYPE,
                     ewmh._NET_WM_WINDOW_TYPE_DIALOG,
                     ewmh._NET_WM_WINDOW_TYPE_DOCK,
                     ewmh._NET_WM_WINDOW_TYPE_DESKTOP};
  atoms = std::make_unique<xcb_atom_t[]>(supported_atoms.size());
  std::copy(supported_atoms.begin(), supported_atoms.end(), atoms.get());
  auto window = xcb_generate_id(conn);
  xcb_create_window(conn, XCB_WINDOW_CLASS_COPY_FROM_PARENT, window, root, 0, 0,
                    1, 1, 0, XCB_WINDOW_CLASS_INPUT_OUTPUT, screen->root_visual,
                    {}, {});
  xcb_ewmh_set_supported(&ewmh, 0, supported_atoms.size(), atoms.get());
  xcb_ewmh_set_supporting_wm_check(&ewmh, root, window);
  xcb_ewmh_set_wm_name(&ewmh, root, strlen("Helios"), "Helios");
  xcb_ewmh_set_supporting_wm_check(&ewmh, root, root);
  xcb_ewmh_set_number_of_desktops(&ewmh, 0, 9);
  xcb_ewmh_set_current_desktop(&ewmh, 0, 1);
  xcb_ewmh_set_active_window(&ewmh, 0, root);
  windows = {};
  for (auto kbd : config.bindings) {
    grab_key(conn, kbd.mod, kbd.keysym, root);
  }
  for (auto wrkspce = 0; wrkspce < 10; ++wrkspce) {
    grab_key(conn, XK_Super_L, XK_0 + wrkspce, root);
  }
  *values.get() = event_mask;
  xcb_void_cookie_t event_mask_cookie =
      xcb_change_window_attributes(conn, root, XCB_CW_EVENT_MASK, values.get());
  xcb_generic_error_t *em_error = xcb_request_check(conn, event_mask_cookie);
  if (!em_error) {
    logger->info("Request Completed Successfully");
  } else {
    auto code = em_error->error_code;
    logger->error("Error in Request: Code {}", code);
  }
  xcb_flush(conn);
  WMConfig::debugConfig(config);
  for (std::string &program : config.startup) {
    spawn(program.c_str());
  }
  if (xcb_cursor_context_new(conn, screen, &cursor_context) != 0) {
    logger->error("Unable to create cursor context");
    throw std::runtime_error("Cursor context creation failed");
  }
  cursor = xcb_cursor_load_cursor(cursor_context, "left_ptr");
  if (cursor == XCB_CURSOR_NONE) {
    logger->error("Failed to load cursor");
    xcb_cursor_context_free(cursor_context);
    throw std::runtime_error("Unable to create cursor context");
  }
  xcb_void_cookie_t cursor_cookie =
      xcb_change_window_attributes(conn, root, XCB_CW_CURSOR, &cursor);
  xcb_generic_error_t *c_error = xcb_request_check(conn, cursor_cookie);
  if (!c_error) {
    logger->info("Request Completed Successfully");
  } else {
    auto code = c_error->error_code;
    logger->error("Error in Request: Code {}", code);
  }
  xcb_flush(conn);
  logger->info("WM initialized, ready to go!");
}
References atoms, WMConfig::General::bindings, config, conn, cursor, cursor_context, WMConfig::debugConfig(), event_mask, ewmh, grab_key(), loadConfig(), logger, root, screen, spawn(), WMConfig::General::startup, supported_atoms, values, and windows.
~WindowManager()
WindowManager::~WindowManager ()
Destructs the WindowManager instance.
Destructor for the WindowManager class.
This destructor is called when the WindowManager instance is no longer needed. It is responsible for cleaning up after the window manager, which includes disconnecting from the X server and freeing any allocated memory.
Cleans up and releases all resources associated with the window manager. This includes clearing supported atoms, destroying all managed windows, freeing the cursor, destroying the root window, disconnecting from the X server, and freeing the cursor context if it exists. Logs a message indicating that the window manager has stopped.
Definition at line 392 of file helios.cpp.
{
  supported_atoms.clear();
  for (auto wdow : windows) {
    xcb_destroy_window(conn, wdow);
  }
  windows.clear();
  xcb_free_cursor(conn, cursor);
  xcb_destroy_window(conn, root);
  xcb_disconnect(conn);
  if (cursor_context) {
    xcb_cursor_context_free(cursor_context);
  }
  logger->info("WM stopped");
}
References conn, cursor, cursor_context, logger, root, supported_atoms, and windows.
Member Function Documentation
handle_destroy_notify()
void WindowManager::handle_destroy_notify (xcb_window_t window) private
Handles a destroy notify event for the given window.
Handles a DestroyNotify event by destroying the window, removing it from the list of windows, re-tiling the windows, and setting the input focus to the last window in the list.
Parameters
window The window that was destroyed.
window The window to handle.
Definition at line 361 of file helios.cpp.
{
  xcb_destroy_window(conn, window);
  auto new_end = std::remove(windows.begin(), windows.end(), window);
  windows.erase(new_end, windows.end());
  xcb_flush(conn);
  tile_windows();
  set_focus(windows.back());
}
References conn, set_focus(), tile_windows(), and windows.
Referenced by run().
handle_enter_notify()
void WindowManager::handle_enter_notify (xcb_window_t window) private
Handles an enter notify event for the given window.
Handles an EnterNotify event.
Parameters
window The window that was entered.
window The window which generated the EnterNotify event.
This function sends a FocusOut event to the previously focused window (if any), and a FocusIn event to the newly focused window. It also updates the EWMH _NET_ACTIVE_WINDOW property.
Definition at line 295 of file helios.cpp.
{
  xcb_set_input_focus(conn, XCB_INPUT_FOCUS_FOLLOW_KEYBOARD, window,
                      XCB_CURRENT_TIME);
  xcb_flush(conn);
}
References conn.
handle_key_press()
void WindowManager::handle_key_press (xcb_key_press_event_t * key_press) private
Handles a key press event for the given key press event.
Handles a KeyPress event by switching to the workspace that corresponds to the number key that was pressed (0-9).
Parameters
key_press The key press event.
If the key press is not a number key with the Mod4 modifier, the function does nothing.
Parameters
key_press The KeyPress event to handle.
Definition at line 308 of file helios.cpp.
{
  for (int i = 0; i <= 9; ++i) {
    if (key_press->state == XK_Alt_L && key_press->detail == XK_0 + i) {
      switch_workspace(i);
      return;
    }
  }
}
References switch_workspace().
Referenced by run().
handle_map_request()
void WindowManager::handle_map_request (xcb_window_t window) private
Handles a map request event for the given window.
Handles a MapRequest event by adding the window to the list of windows, mapping the window, setting the border width and color, setting the input focus to the window, and re-tiling the windows.
Parameters
window The window that requested the map.
window The window to handle.
Definition at line 324 of file helios.cpp.
{
  windows.push_back(window);
  auto cookie = xcb_get_window_attributes(conn, window);
  xcb_generic_error_t **e = nullptr;
  auto _attr_reply = xcb_get_window_attributes_reply(conn, cookie, e);
  if (_attr_reply->override_redirect) {
    return;
  }
  delete e;
  xcb_map_window(conn, window);
  auto border_width = static_cast<uint32_t>(config.border.width);
  uint32_t border_values[2] = {border_width, border_width};
  xcb_configure_window(conn, window, XCB_CONFIG_WINDOW_BORDER_WIDTH,
                       border_values);
  xcb_flush(conn);
  set_window_border_color(window, config.border.color);
  xcb_set_input_focus(conn, XCB_INPUT_FOCUS_POINTER_ROOT, window,
                      XCB_CURRENT_TIME);
  xcb_flush(conn);
  tile_windows();
}
References WMConfig::General::border, WMConfig::Border::color, config, conn, set_window_border_color(), tile_windows(), WMConfig::Border::width, and windows.
Referenced by run().
handle_unmap_request()
void WindowManager::handle_unmap_request (xcb_window_t window) private
Handles an unmap request event for the given window.
Handles an UnmapNotify event by un-mapping the window, setting the input focus to the last window in the list, and re-tiling the windows.
Parameters
window The window that requested the unmap.
window The window to handle.
Definition at line 376 of file helios.cpp.
{
  xcb_unmap_window(conn, window);
  xcb_flush(conn);
  set_focus(windows.back());
  tile_windows();
}
References conn, set_focus(), tile_windows(), and windows.
Referenced by run().
run()
void WindowManager::run ()
Starts the window manager.
The main loop of the window manager.
This function is called when the window manager is started. It sets up the event loop, which is the main loop of the window manager. This loop will continue to run until the window manager is stopped.
Waits for events and handles them accordingly. Events are handled in the following order:
MapRequest - Maps the window and adds it to the list of managed windows.
UnmapNotify - Unmaps the window and removes it from the list of managed windows.
DestroyNotify - Destroys the window and removes it from the list of managed windows.
EnterNotify - Sets the input focus to the window that the pointer is currently over.
KeyPress - Switches to the specified workspace when a number key with the Mod4 modifier is pressed.
If the event is not one of the above, the window manager will log an error message and break out of the main loop.
The window manager will also log an error message if the event is invalid.
Definition at line 428 of file helios.cpp.
{
  for (;;) {
    xcb_generic_event_t *event = xcb_wait_for_event(conn);
    logger->info("Event Happened!");
    if (!event) {
      logger->error("Event is invalid");
      break;
    }
    switch (event->response_type & ~0x80) {
    case XCB_MAP_REQUEST: {
      logger->info("found map-request event");
      auto *map_request = (xcb_map_request_event_t *)event;
      handle_map_request(map_request->window);
      break;
    }
    case XCB_UNMAP_NOTIFY: {
      logger->info("found unmap-notify event");
      auto *unmap_notify = (xcb_unmap_notify_event_t *)event;
      handle_unmap_request(unmap_notify->window);
      break;
    }
    case XCB_DESTROY_NOTIFY: {
      logger->info("found destory-notify event");
      auto destroy_notify = (xcb_destroy_notify_event_t *)event;
      handle_destroy_notify(destroy_notify->window);
      break;
    }
    case XCB_ENTER_NOTIFY: {
      logger->info("found enter-notify event");
      auto enter_notify = (xcb_enter_notify_event_t *)event;
      set_focus(enter_notify->root);
      break;
    }
    case XCB_KEY_PRESS: {
      logger->info("found key-press event");
      auto key_press = (xcb_key_press_event_t *)event;
      handle_key_press(key_press);
      break;
    }
    }
    free(event);
    xcb_flush(conn);
  }
}
References conn, handle_destroy_notify(), handle_key_press(), handle_map_request(), handle_unmap_request(), logger, and set_focus().
Referenced by main().
set_focus()
void WindowManager::set_focus (xcb_window_t window) private
Sets the focus of the window manager to the given window.
Sets the focus to a given window.
Parameters
window The window whose focus to set.
window The window to set the focus to.
Definition at line 267 of file helios.cpp.
{
  xcb_set_input_focus(conn, XCB_INPUT_FOCUS_POINTER_ROOT, window,
                      XCB_CURRENT_TIME);
  xcb_flush(conn);
}
References conn.
Referenced by handle_destroy_notify(), handle_unmap_request(), and run().
set_window_border_color()
void WindowManager::set_window_border_color (xcb_window_t window, uint32_t color) private
Sets the border color of the window to the given color.
Sets the border color of a window.
Parameters
window The window whose border color to set.
color The color to set the border color to.
window The X window for which to set the border color.
color The color to set the border to, in 32-bit ARGB format.
Definition at line 256 of file helios.cpp.
{
  xcb_change_window_attributes(conn, window, XCB_CW_BORDER_PIXEL, &color);
  xcb_flush(conn);
}
References conn.
Referenced by handle_map_request(), and tile_windows().
switch_workspace()
void WindowManager::switch_workspace (uint32_t i) private
Switches the workspace of the window manager to the given workspace.
Switches to the workspace with the given index.
Parameters
i The workspace number to switch to.
i The index of the workspace to switch to.
Definition at line 279 of file helios.cpp.
{
  uint32_t data[] = {i};
  xcb_change_property(conn, XCB_FOCUS_IN, screen->root, ewmh._NET_WM_DESKTOP,
                      XCB_ATOM_CARDINAL, 32, 1, data);
  xcb_flush(conn);
}
References conn, ewmh, and screen.
Referenced by handle_key_press().
tile_windows()
void WindowManager::tile_windows () private
Tiles all windows in the current workspace.
Tile all windows in the list in a non-overlapping manner across the screen.
The tiling algorithm is as follows:
Split the screen in half horizontally.
Place the first window in the top half of the screen.
For each subsequent window: a. Find the window with the largest area. b. Split that window in half, either horizontally or vertically, depending on the previous split direction. c. Place the new window in the newly created space. d. Switch the split direction.
Definition at line 163 of file helios.cpp.
{
  int num_windows = windows.size();
  if (num_windows == 0)
    return;
  int screen_width = screen->width_in_pixels;
  int screen_height = screen->height_in_pixels;
  int gap = config.window.gap;
  int border_width = config.border.width;
  if (num_windows == 1) {
    uint32_t values[4] = {static_cast<uint32_t>(gap),
                          static_cast<uint32_t>(gap),
                          static_cast<uint32_t>(screen_width - 2 * gap),
                          static_cast<uint32_t>(screen_height - 2 * gap)};
    uint32_t border_values[1] = {static_cast<uint32_t>(border_width)};
    xcb_configure_window(conn, windows[0], XCB_CONFIG_WINDOW_BORDER_WIDTH,
                         border_values);
    xcb_configure_window(conn, windows[0],
                         XCB_CONFIG_WINDOW_X | XCB_CONFIG_WINDOW_Y |
                             XCB_CONFIG_WINDOW_WIDTH | XCB_CONFIG_WINDOW_HEIGHT,
                         values);
    set_window_border_color(windows[0], config.border.color);
    xcb_flush(conn);
    return;
  }
  struct WindowRect {
    int x, y, width, height;
  };
  std::vector<WindowRect> window_rects(num_windows);
  window_rects[0] = {gap, gap, screen_width - 2 * gap, screen_height - 2 * gap};
  bool split_horizontal = false;
  for (int i = 1; i < num_windows; i++) {
    int largest_idx = i - 1;
    int largest_area = 0;
    for (int j = 0; j < i; j++) {
      int area = window_rects[j].width * window_rects[j].height;
      if (area > largest_area) {
        largest_area = area;
        largest_idx = j;
      }
    }
    WindowRect &to_split = window_rects[largest_idx];
    WindowRect &new_window = window_rects[i];
    if (split_horizontal) {
      int new_height = (to_split.height - gap) / 2;
      new_window = {to_split.x, to_split.y + new_height + gap, to_split.width,
                    to_split.height - new_height - gap};
      to_split.height = new_height;
    } else {
      int new_width = (to_split.width - gap) / 2;
      new_window = {to_split.x + new_width + gap, to_split.y,
                    to_split.width - new_width - gap, to_split.height};
      to_split.width = new_width;
    }
    split_horizontal = !split_horizontal;
  }
  for (int i = 0; i < num_windows; i++) {
    const auto &rect = window_rects[i];
    uint32_t values[4] = {
        static_cast<uint32_t>(rect.x), static_cast<uint32_t>(rect.y),
        static_cast<uint32_t>(rect.width), static_cast<uint32_t>(rect.height)};
    uint32_t border_values[1] = {static_cast<uint32_t>(border_width)};
    xcb_configure_window(conn, windows[i], XCB_CONFIG_WINDOW_BORDER_WIDTH,
                         border_values);
    xcb_configure_window(conn, windows[i],
                         XCB_CONFIG_WINDOW_X | XCB_CONFIG_WINDOW_Y |
                             XCB_CONFIG_WINDOW_WIDTH | XCB_CONFIG_WINDOW_HEIGHT,
                         values);
    set_window_border_color(windows[i], config.border.color);
  }
  xcb_flush(conn);
}
References WMConfig::General::border, WMConfig::Border::color, config, conn, WMConfig::Window::gap, screen, set_window_border_color(), values, WMConfig::Border::width, WMConfig::General::window, and windows.
Referenced by handle_destroy_notify(), handle_map_request(), and handle_unmap_request().
Member Data Documentation
atoms
std::unique_ptr<xcb_atom_t[]> WindowManager::atoms private
A unique pointer to an array of xcb_atom_t values.
This array is used to store the atoms that the window manager supports.
Definition at line 138 of file helios.h.
Referenced by WindowManager().
config
Config WindowManager::config private
The configuration for the window manager.
This configuration contains information such as the colors to use for the window manager and the fonts to use.
Definition at line 71 of file helios.h.
Referenced by handle_map_request(), tile_windows(), and WindowManager().
conn
xcb_connection_t* WindowManager::conn private
The XCB connection to the X server.
This is the connection that the window manager uses to communicate with the X server.
Definition at line 37 of file helios.h.
Referenced by handle_destroy_notify(), handle_enter_notify(), handle_map_request(), handle_unmap_request(), run(), set_focus(), set_window_border_color(), switch_workspace(), tile_windows(), WindowManager(), and ~WindowManager().
current_window
int WindowManager::current_window private
The index of the window that currently has focus.
This is the index of the window in the windows vector that currently has focus.
Definition at line 88 of file helios.h.
cursor
xcb_cursor_t WindowManager::cursor private
The cursor ID for the window manager's cursor.
The cursor ID is an ID that is used to identify the window manager's cursor.
Definition at line 96 of file helios.h.
Referenced by WindowManager(), and ~WindowManager().
cursor_context
xcb_cursor_context_t* WindowManager::cursor_context private
The context for the window manager's cursor.
The context is a structure that contains information about the cursor such as its shape and its color.
Definition at line 104 of file helios.h.
Referenced by WindowManager(), and ~WindowManager().
event_mask
uint32_t WindowManager::event_mask private
Initial value:
=
      XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT |
      XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY | XCB_EVENT_MASK_BUTTON_PRESS |
      XCB_EVENT_MASK_BUTTON_RELEASE | XCB_EVENT_MASK_POINTER_MOTION |
      XCB_EVENT_MASK_KEY_PRESS | XCB_EVENT_MASK_KEY_RELEASE | XCB_EVENT_MASK_ENTER_WINDOW
The event mask for the window manager.
The event mask is a bit mask that specifies which events the window manager should receive. The window manager will receive events for all windows that have this mask.
Definition at line 113 of file helios.h.
Referenced by WindowManager().
ewmh
xcb_ewmh_connection_t WindowManager::ewmh private
The EWMH connection for the window manager.
The EWMH connection is a structure that contains information about the window manager's connection to the X server.
Definition at line 146 of file helios.h.
Referenced by switch_workspace(), and WindowManager().
logger
std::shared_ptr<spdlog::logger> WindowManager::logger private
Initial value:
=
      spdlog::basic_logger_mt("Helios", "logs.txt")
The logger for the window manager.
The logger is a mechanism for logging messages. The window manager uses the logger to log messages about what it is doing.
Definition at line 79 of file helios.h.
Referenced by run(), WindowManager(), and ~WindowManager().
root
xcb_window_t WindowManager::root private
The root window of the X server.
The root window is the parent window of all other windows on the X server.
Definition at line 53 of file helios.h.
Referenced by WindowManager(), and ~WindowManager().
screen
xcb_screen_t* WindowManager::screen private
The screen structure for the screen that the window manager is managing.
This structure contains information about the screen such as its width and height.
Definition at line 46 of file helios.h.
Referenced by switch_workspace(), tile_windows(), and WindowManager().
supported_atoms
std::vector<xcb_atom_t> WindowManager::supported_atoms = {} private
A vector of supported atoms for the window manager.
This vector contains the atoms that the window manager supports.
Definition at line 131 of file helios.h.
{};
Referenced by WindowManager(), and ~WindowManager().
values
std::unique_ptr<uint32_t[]> WindowManager::values private
A unique pointer to an array of uint32_t values.
This array is used to store values that are used by the window manager.
Definition at line 124 of file helios.h.
Referenced by tile_windows(), and WindowManager().
windows
std::vector<xcb_window_t> WindowManager::windows private
A vector of window IDs that the window manager is currently managing.
This vector contains the IDs of all windows that the window manager has been asked to manage. The window manager will receive events for these windows and will be able to control them.
Definition at line 63 of file helios.h.
Referenced by handle_destroy_notify(), handle_map_request(), handle_unmap_request(), tile_windows(), WindowManager(), and ~WindowManager().
The documentation for this class was generated from the following files:
src/include/helios.h
src/helios.cpp